### ISSUE TITLE
Support Kehrschleifenmodul

### ISSUE THREAD

**Issue by eyip002** [trinnguyen/bahndsl#21]
Support the definition of Kehrschleifenmodul (loop reverser) so that its state can be read at run-time:
```
reversers master
   reverser1 10051 blockA     # reverser1 state is in CV 10051 of the master board and controls blockA
   reverser2 20051 blockB     # reverser2 state is in CV 20051 of the master board and controls blockB
end
```

This information is exported into the track YAML file under its respective board:
```
boards:
  - id: master
    reversers:
      - id: reverser1
        cv: 10051
        block: blockA
      - id: reverser2
        cv: 20051
        block: blockB
```
